# Generated by Django 5.0.6 on 2024-06-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0002_posts_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='userId',
        ),
    ]
